# Generated by Django 3.1.5 on 2021-01-16 12:40

from django.db import migrations, models
import django.db.models.deletion
import enif_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('enif_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enif_Session',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(default=enif_app.models.create_session_token, max_length=50, verbose_name='Token')),
                ('Source', models.CharField(max_length=50, verbose_name='Quelle')),
                ('Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('Valid_Until', models.DateTimeField(default=enif_app.models.set_valid_until, verbose_name='Gültig bis')),
                ('LU', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('D', models.BooleanField(default=False, verbose_name='Gelöscht')),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Name')),
                ('Tag', models.CharField(max_length=30, unique=True, verbose_name='Tag')),
                ('Des', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beschreibung')),
                ('Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('LU', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('D', models.BooleanField(default=False, verbose_name='Gelöscht')),
            ],
        ),
        migrations.CreateModel(
            name='Stopword',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Pattern', models.CharField(max_length=50, unique=True, verbose_name='Pattern')),
                ('Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('LU', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('D', models.BooleanField(default=False, verbose_name='Gelöscht')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_Pattern', models.CharField(max_length=50, unique=True, verbose_name='Pattern')),
                ('Intent_ACCURACY', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Genauigkeit')),
                ('User_Feedback', models.BooleanField(default=None, null=True, verbose_name='Hilfreich')),
                ('Request_Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('Request_LU', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('Request_D', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('Intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enif_app.intent')),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enif_app.enif_session')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Pattern', models.CharField(max_length=50, verbose_name='Pattern')),
                ('Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('LU', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('D', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('Intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enif_app.intent')),
            ],
            options={
                'unique_together': {('Intent', 'Pattern')},
            },
        ),
    ]
