# Generated by Django 3.1.5 on 2021-01-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enif_app', '0002_enif_session_intent_pattern_request_stopword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Enif_Request',
        ),
    ]
