# Generated by Django 3.1.5 on 2021-01-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enif_app', '0003_auto_20210116_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Host', models.CharField(max_length=50, verbose_name='Host')),
                ('Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('LU', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('D', models.BooleanField(default=False, verbose_name='Gelöscht')),
            ],
        ),
    ]
