# Generated by Django 3.1.5 on 2021-01-16 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enif_app', '0005_auto_20210116_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enif_request',
            old_name='Request_D',
            new_name='D',
        ),
        migrations.RenameField(
            model_name='enif_request',
            old_name='Request_Inserted',
            new_name='Inserted',
        ),
        migrations.RenameField(
            model_name='enif_request',
            old_name='Request_LU',
            new_name='LU',
        ),
        migrations.AlterField(
            model_name='enif_session',
            name='Valid_Until',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 15, 48, 3, 882850), verbose_name='Gültig bis'),
        ),
    ]
