# Generated by Django 3.1.5 on 2021-01-16 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enif_app', '0007_auto_20210116_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enif_request',
            name='Pattern',
            field=models.CharField(max_length=50, verbose_name='Pattern'),
        ),
        migrations.AlterField(
            model_name='enif_session',
            name='Valid_Until',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 16, 53, 25, 99848), verbose_name='Gültig bis'),
        ),
    ]
