# Generated by Django 3.1.5 on 2021-01-16 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enif_app', '0008_auto_20210116_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enif_request',
            name='Intent_ACCURACY',
            field=models.FloatField(blank=True, null=True, verbose_name='Genauigkeit'),
        ),
        migrations.AlterField(
            model_name='enif_session',
            name='Valid_Until',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 21, 44, 50, 124367), verbose_name='Gültig bis'),
        ),
    ]
