# Generated by Django 3.1.5 on 2021-01-16 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enif_app', '0010_auto_20210116_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='enif_request',
            name='Predict',
            field=models.BooleanField(default=True, verbose_name='Verstehen'),
        ),
        migrations.AddField(
            model_name='enif_session',
            name='User_Feedback',
            field=models.BooleanField(default=None, null=True, verbose_name='Hilfreich'),
        ),
        migrations.AlterField(
            model_name='enif_session',
            name='Valid_Until',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 22, 31, 3, 410275), verbose_name='Gültig bis'),
        ),
        migrations.CreateModel(
            name='Enif_Answers',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Antwort')),
                ('Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('LU', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('D', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('Intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enif_app.intent')),
            ],
        ),
    ]
