# Generated by Django 3.1.5 on 2021-01-17 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enif_app', '0011_auto_20210116_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enif_System_Answer',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Antwort')),
                ('Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('LU', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('D', models.BooleanField(default=False, verbose_name='Gelöscht')),
            ],
        ),
        migrations.RenameModel(
            old_name='Enif_Answers',
            new_name='Enif_Intent_Answer',
        ),
        migrations.AlterField(
            model_name='enif_session',
            name='Valid_Until',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 12, 0, 12, 363732), verbose_name='Gültig bis'),
        ),
    ]
