# Generated by Django 3.1.5 on 2021-01-17 11:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enif_app', '0012_auto_20210117_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enif_session',
            name='Valid_Until',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 12, 12, 32, 271863), verbose_name='Gültig bis'),
        ),
        migrations.CreateModel(
            name='Enif_Session_History',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('LU', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('D', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('Enif_System_Answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enif_app.enif_system_answer')),
                ('Intent_Answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enif_app.enif_intent_answer')),
                ('Request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enif_app.enif_request')),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enif_app.enif_session')),
            ],
        ),
    ]
