# Generated by Django 3.1.5 on 2021-01-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enif_app', '0013_auto_20210117_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enif_session',
            name='Valid_Until',
            field=models.DateTimeField(verbose_name='Gültig bis'),
        ),
    ]
